CREATE TABLE IF NOT EXISTS Password(
  id INTEGER PRIMARY KEY,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Secured(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Fields(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  secured_id INTEGER NOT NULL,
  field_name TEXT NOT NULL,
  field_value TEXT NOT NULL,
  FOREIGN KEY (secured_id) REFERENCES Secured(id) ON DELETE CASCADE
);
